kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: openjdk:17
    environment:
      USER:
        from_secret: username
      PASSWORD:
        from_secret: password
    commands:
      - ./gradlew publish -Ppublish-username=$USER -Ppublish-password=$PASSWORD
      - "echo 10 most recent commits: > note.txt"
      - "git log --pretty=tformat:%B -n10 >> note.txt"
      - "rm build/libs/*-dev.jar"
  - name: release
    image: unascribed/drone-gitea-release
    settings:
      api_key:
        from_secret: gitea_key
      base_url: https://git.sleeping.town
      files:
        - build/libs/aleph-*.jar
      title: Dev Build
      prerelease: true
      tag: dev
      note: note.txt
      allow_edit: true
    when:
      branch:
        - trunk